name: Build artifacts

on: push

jobs:
    build:
        name: Build artifacts
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2
            -   name: Setup Go
                uses: actions/setup-go@v2
                with:
                    go-version: '1.15.8'
            -   name: Download dependencies
                run: go mod download
            -   name: Build binaries
                run: hack/build.sh
            -   uses: actions/upload-artifact@v2
                with:
                    name: chart-verifier
                    path: out/chart-verifier